version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    ports:
      - 5000:5000
    volumes:
      - ..:/app
    command: gunicorn --log-level debug -w 4 -b 0.0.0.0:5000 "main:create_app()"